version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: koladi_app_local
    volumes:
      - .:/var/www
    env_file:
      - .env
    entrypoint: ["/usr/local/bin/entrypoint.local.sh"]
    command: ["php-fpm"]  
    depends_on:
      - db
    networks:
      - koladi_net

  nginx:
    image: nginx:alpine
    container_name: koladi_nginx_local
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - koladi_net

  db:
    image: postgres:15
    container_name: koladi_db_local
    environment:
      POSTGRES_DB: koladi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata_local:/var/lib/postgresql/data
    networks:
      - koladi_net

networks:
  koladi_net:

volumes:
  pgdata_local:
