version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: koladi_app
    env_file:
      - .env
    entrypoint: entrypoint.local.sh
    command: php-fpm
    depends_on:
      - db
    networks:
      - koladi_net

  nginx:
    image: nginx:alpine
    container_name: koladi_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - koladi_net

  db:
    image: postgres:15
    container_name: koladi_db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - koladi_net

networks:
  koladi_net:

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: /path/to/backup/location  # Path di host untuk backup
      o: bind
